#+STARTUP: showall
* My Emacs Configuration
To use this Emacs configuration, simply run the following command in
your terminal before BACKUP your own configurations.
#+BEGIN_SRC shell
  cd ~ 
  git clone https://github.com/gykxjtu/emacs.d.git .emacs.d
#+END_SRC
** For MacOS X
   Since =pdf-tools= is not officially supported on MacOS X, you can
   set comment the following codes in =.emacs.d/elisp/init-config.el=
   to avoid errors during compiling on your Mac.
#+BEGIN_SRC emacs-lisp
  (unless (eq system-type 'darwin)
    ;; MacOS X is not officially supported.
    (use-package pdf-tools
      :ensure
      :config (progn
		(pdf-tools-install))))
#+END_SRC
** About TeX
   Since you have to manually add
   #+BEGIN_SRC emacs-lisp
     (setenv "PATH" (concat (getenv "PATH") ":" "/usr/local/bin"))
   #+END_SRC
   to your configuration file on your MacOS, make sure =latex= binary
   is located at =/usr/local/bin=, which is MacTeX's default option. If
   you install =TeXLive= with terminal, simply modify the string
   parameter to match your =latex= binary location.
** About =auto-complete-clang= and auto-complete-clang-async
   =ACC= is a very nice package to help you with completion while
   coding. However, it may sometimes be less "smooth" than =ACCA=
   which calls a 3rd party process as server while completion. ACCA
   can now only be compiled on Linux (eg. Manjaro).
